name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install packages
      run: sudo apt-get install -y wget libgmp-dev libmpfr-dev m4
    - name: Run a multi-line script
      run: |
        ./bootstrap.sh
